env:
  browser: true
  es2021: true
  node: true
  jest: true
settings:
  react:
    version: 'detect'
extends:
  - 'eslint:recommended'
  - 'next'
  - 'next/core-web-vitals'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:jsx-a11y/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:jest/recommended'
  - 'plugin:testing-library/react'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  'react/prop-types': 'off'
  'react/display-name': 'off'
  'import/no-unresolved': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
